sudo: false
language: python
dist: trusty

matrix:
  include:
    # Default Python
    - env: TOXENV=flake8
    - env: TOXENV=markdown-lint
      # Travis only gives us Node.js version 8 so we must use an older
      # version of markdownlint. To declare a newer node.js version we
      # lose the ability to have Python as the lang and install tox.
      # If/when the default node version gets updated, remove the
      # version restriction on markdownlint.
      before_install: npm install -g markdownlint-cli@0.21.0
    # Until Linkchecker is updated to Python 3, we will have skip this test.
    # Watch https://github.com/linkchecker/linkchecker for updates.
    # - env: TOXENV=linkchecker
    #  python: '2.7'
    - env: TOXENV=jshint
      before_install: npm install -g jshint
    - env: TOXENV=csslint
      before_install: npm install -g csslint
    # Python version specific
    - python: '3.5'
      env: TOXENV=py35-integration
    - python: '3.5'
      env: TOXENV=py35-min-req
    - python: '3.5'
      env: TOXENV=py35-unittests
    - python: '3.6'
      env: TOXENV=py36-integration
    - python: '3.6'
      env: TOXENV=py36-min-req
    - python: '3.6'
      env: TOXENV=py36-unittests
    - python: '3.7'
      env: TOXENV=py37-integration
      dist: xenial
      sudo: true
    - python: '3.7'
      env: TOXENV=py37-min-req
      dist: xenial
      sudo: true
    - python: '3.7'
      env: TOXENV=py37-unittests
      dist: xenial
      sudo: true
    - python: '3.8'
      env: TOXENV=py38-integration
      dist: xenial
      sudo: true
    - python: '3.8'
      env: TOXENV=py38-min-req
      dist: xenial
      sudo: true
    - python: '3.8'
      env: TOXENV=py38-unittests
      dist: xenial
      sudo: true
    - python: 'pypy3'
      env: TOXENV=pypy3-integration
    - python: 'pypy3'
      env: TOXENV=pypy3-min-req
    - python: 'pypy3'
      env: TOXENV=pypy3-unittests

install:
  - pip install 'virtualenv<20.0.0'
  - pip install codecov
  - pip install tox

script:
  - git clean -f -d -x
  - pip freeze
  - tox

after_success: codecov

deploy:
  provider: pypi
  user: mkdocsdeploy
  distributions: "sdist bdist_wheel"
  password:
    secure: b4f6y1xw5B/RXXnOu6JIaNcgOBZ0/CkNaMeEXsoQSewYZNwobLPYALY9WaaOblarwrVa5NRD3e4x6SoL1/1NzQxfhCNMn7L82sssmtevnK+mSuUp4IZQa8WKyz+xLfnk28TlHgQbctAU9NaeQ6GuEflTRD7Bp8+xJ1C7h+yBUnw=
  on:
    tags: true
    repo: mkdocs/mkdocs
    condition: "$TOXENV = py37-integration"
