build: false
environment:
  matrix:
    - TOXENV: py35-integration
    - TOXENV: py35-min-req
    - TOXENV: py35-unittests
    - TOXENV: py36-integration
    - TOXENV: py36-min-req
    - TOXENV: py36-unittests
    - TOXENV: py37-integration
    - TOXENV: py37-min-req
    - TOXENV: py37-unittests
    - TOXENV: py38-integration
    - TOXENV: py38-min-req
    - TOXENV: py38-unittests
    - TOXENV: flake8
init:
  - "ECHO %TOXENV%"
install:
  - "c:\\python37\\Scripts\\pip install tox"
test_script:
  - "git clean -f -d -x"
  - "c:\\python37\\Scripts\\tox --version"
  - "c:\\python37\\Scripts\\pip --version"
  - "c:\\python37\\Scripts\\tox"
